version: "3"
services:
    postgresql:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_USER: test_user
            POSTGRES_DB: test_db
            POSTGRES_PASSWORD: ${PASSWORD}
        volumes:
            - ./pgbouncer.sql:/docker-entrypoint-initdb.d/pgbouncer.sql

    pgbouncer:
        build: .
        environment:
            USER: test_user
            DBNAME: test_db
            PASSWORD: ${PASSWORD}
        links:
            - postgresql:db
        command: pgbouncer -v /etc/pgbouncer/pgbouncer.ini

    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        environment:
            USER: test_user
            DBNAME: test_db
            PASSWORD: ${PASSWORD}
        links:
            - postgresql
            - pgbouncer:db
