FROM bearstech/debian:stretch

RUN apt-get update &&\
        apt-get install -y \
            postgresql-client \
    && rm -rf /var/lib/apt/lists/*

CMD PGPASSWORD=${PASSWORD} psql --host=db --username=${USER} ${DBNAME}
