version: "3"
services:
    postgresql:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: test_user
            POSTGRES_DB: test_db
            POSTGRES_PASSWORD: ${PASSWORD}

    pgbouncer:
        build: .
        environment:
            USER: test_user
            DBNAME: test_db
            PASSWORD: ${PASSWORD}
        links:
            - postgresql:db

    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        environment:
            USER: test_user
            DBNAME: test_db
            PASSWORD: ${PASSWORD}
        links:
            - pgbouncer:db
