version: "3"
services:
    postgresql:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PASSWORD}
            POSTGRES_USER: test_user
            POSTGRES_DB: test_db

    pgbouncer:
        build: .
        environment:
            DBNAME: test_db
            USER: test_user
            PASSWORD: ${PASSWORD}
        links:
            - postgresql:db
        expose:
            - 5432
        ports:
            - 5432

    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        environment:
            PASSWORD: ${PASSWORD}
            USER: test_user
            DBNAME: test_db
        links:
            - pgbouncer:db
